# Generated by Django 5.0.4 on 2024-05-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address2',
            new_name='shipping_apartment',
        ),
    ]
