# Generated by Django 6.0.4 on 2026-04-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_date_paid_order_phone_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payfastpayment',
            name='pf_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
