# Generated by Django 6.0.4 on 2026-06-18 10:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payfastpayment_pf_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_booked',
            field=models.CharField(blank=True, default='', help_text="Which courier you actually booked via Bob Go (e.g., 'Courier Guy', 'MTE'). Update after booking.", max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_actual_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='What we actually pay the courier (internal — never shown to customer)', max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount charged to customer for shipping', max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service_code',
            field=models.CharField(blank=True, choices=[('economy', 'Economy Delivery (5-7 days)'), ('standard', 'Standard Delivery (3-5 days)'), ('express', 'Express Delivery (2-3 days)')], default='', help_text='Shipping tier the customer selected at checkout', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service_name',
            field=models.CharField(blank=True, default='', help_text='Human-readable shipping service name', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', help_text='Tracking number from the courier after booking via Bob Go', max_length=100),
        ),
    ]
