# Generated by Django 5.0.4 on 2024-05-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proof_of_payment',
            field=models.FileField(default=False, upload_to='media/uploads/payments/'),
        ),
    ]
