# Generated by Django 6.0.4 on 2026-06-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_courier_booked_order_shipping_actual_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_province',
            field=models.CharField(blank=True, choices=[('Gauteng', 'Gauteng'), ('Western Cape', 'Western Cape'), ('KwaZulu-Natal', 'KwaZulu-Natal'), ('Eastern Cape', 'Eastern Cape'), ('Free State', 'Free State'), ('Limpopo', 'Limpopo'), ('Mpumalanga', 'Mpumalanga'), ('North West', 'North West'), ('Northern Cape', 'Northern Cape')], help_text='South African province for delivery', max_length=20, null=True),
        ),
    ]
