# Generated by Django 6.0.4 on 2026-06-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_shippingaddress_shipping_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_point_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('ready_for_pickup', 'Ready for Pickup'), ('shipped', 'Shipped'), ('collected', 'Collected'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_country',
            field=models.CharField(blank=True, default='South Africa', max_length=255, null=True),
        ),
    ]
