# Generated by Django 5.0.4 on 2024-07-16 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payfastpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payfastpayment',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
