# Generated by Django 5.0.4 on 2024-07-23 23:42

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payfastpayment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='proof_of_payment',
        ),
        migrations.AddField(
            model_name='payfastpayment',
            name='itn_payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payfastpayment',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payfastpayment',
            name='created_at',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='payfastpayment',
            name='updated_at',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
