# Generated by Django 6.0.4 on 2026-06-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_date_collected_order_date_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_point_code',
            field=models.CharField(blank=True, choices=[('', 'N/A (courier delivery)'), ('office', 'Marvelously Green Office'), ('rrk_pharmacy', 'RRK Pharmacy')], default='', help_text='Pickup point if customer chose Collection', max_length=20),
        ),
    ]
