# Generated by Django 5.0.4 on 2024-07-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_order_proof_of_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payfastpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payfastpayment',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payfastpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
