# Generated by Django 5.0.4 on 2024-07-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_payfastpayment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payfastpayment',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
