# Generated by Django 5.0.4 on 2024-07-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_payfastpayment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payfastpayment',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
