# Generated by Django 6.0.4 on 2026-04-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
