# Generated by Django 5.0.4 on 2025-06-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='use',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
