# Generated by Django 5.0.4 on 2025-06-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
