# Generated by Django 5.0.4 on 2025-06-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0002_alter_product_benefits_alter_product_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
