# Generated by Django 5.0.4 on 2025-06-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0002_product_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
