# Generated by Django 5.0.4 on 2025-06-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0003_alter_product_full_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='full_description',
            new_name='benefits',
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
