# Generated by Django 5.0.4 on 2025-08-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0003_alter_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='amount_off',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
