# Generated by Django 5.0.4 on 2025-06-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0004_rename_full_description_product_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
