# Generated by Django 6.0.4 on 2026-07-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='URL-friendly version of name — auto-generated if left blank', max_length=200, unique=True),
        ),
    ]
