# Generated by Django 5.0.4 on 2025-08-06 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0004_discountcode_amount_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_codes', to='greenmarv.influencer'),
        ),
    ]
