# Generated by Django 6.0.4 on 2026-08-14 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Subscriber's email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('signup_channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', help_text='How they subscribed (for segmentation)', max_length=10)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if user unsubscribes')),
                ('welcome_code_used', models.BooleanField(default=False, help_text='Set to True when they use their 10% off code')),
                ('source_page', models.CharField(blank=True, help_text='Which page they signed up from (home, checkout, etc)', max_length=100)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-date_subscribed'],
            },
        ),
    ]
