# Generated by Django 5.0.4 on 2026-01-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0005_alter_discountcode_influencer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale',
            new_name='is_sale',
        ),
        migrations.AddField(
            model_name='product',
            name='badge_text',
            field=models.CharField(default='100% Organic', help_text='e.g., 100% Organic or Best Seller', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_1',
            field=models.CharField(blank=True, help_text='e.g., ⚡ Fast Acting', max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_2',
            field=models.CharField(blank=True, help_text='e.g., 💧 Daily Use', max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_3',
            field=models.CharField(blank=True, help_text='e.g., 🌿 100ml', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
