# Generated by Django 5.0.4 on 2024-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0006_alter_discountcode_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='commission_rate',
            field=models.IntegerField(default=0),
        ),
    ]
