# Generated by Django 6.0.4 on 2026-08-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0006_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='amount_off',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed Rand amount off. Use this OR discount_percentage.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_percentage',
            field=models.IntegerField(default=0, help_text='Percentage off. Use this OR amount_off, not both.'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='total_before_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Cumulative Rand value of orders that used this code.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this code has been used.'),
        ),
    ]
