# Generated by Django 5.0.4 on 2024-09-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0007_alter_discountcode_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='usage_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
