# Generated by Django 5.0.4 on 2024-09-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0008_alter_discountcode_usage_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='total_before_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
