# Generated by Django 5.0.4 on 2024-11-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarv', '0010_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
